routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function(){
    return view('auth.login');
});

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\RolesController;
use App\Http\Controllers\Admin\PermissionsController;
use App\Http\Controllers\Admin\UsersRolesController;
use App\Http\Controllers\Admin\UsersPermissionsController;
use App\Http\Controllers\Admin\TipoCambiosController;


Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    // 'namespace' => 'Admin',
    'middleware' => 'auth'
], function(){
    Route::get('/', [TipoCambiosController::class, 'index']);
    // Usuarios
    Route::resource('users', UsersController::class);
    // // Roles
    Route::resource('roles', RolesController::class)->except(['show']);
    // // Permisos
    Route::resource('permissions', PermissionsController::class)->only(['index', 'edit', 'update']);
    // // Actualizar Roles de Usuario y Permisos de Usuario
    Route::middleware('role:admin')
        ->put('users/{user}/roles', [UsersRolesController::class, 'update'])
        ->name('users.roles.update');
    Route::middleware('role:admin')
        ->put('users/{user}/permissions', [UsersPermissionsController::class, 'update'])
        ->name('users.permissions.update');
    /********************** INICIO MÓDULOS *********************/
    Route::resource('tipocambio', TipoCambiosController::class)->except(['show']);
    /**********************   FIN MÓDULOS  *********************/
});

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RolesController extends Controller
{
    public function index()
    {
        $this->authorize('view', new Role);
        return view('admin.roles.index', ['roles' => Role::all()]);
    }

    public function create()
    {
        $this->authorize('create', $role = new Role);
        $role = new Role;
        return view('admin.roles.create', [
            'role' => $role,
            'permissions' => Permission::pluck('name', 'id')
        ]);
    }

    public function store(Request $request)
    {
        $this->authorize('create', new Role);
        $data = $request->validate([
            'name' => 'required|unique:roles',
            'display_name' => 'required',
            'guard_name' => 'required'
        ],[
            'name.required' => 'El campo identificador es obligatorio',
            'name.unique' => 'Este identificador ya ha sido registrado',
            'display_name.required' => 'El campo nombre es obligatorio',
            'guard_name.required' => 'El campo nombre de guardia es obligatorio'
        ]);

        $role = Role::create($data);

        if ($request->has('permissions')) {
            $role->givePermissionTo($request->permissions);
        }

        return redirect()->route('admin.roles.index', $role)->with('success','El rol fue creado correctamente');
    }

    public function edit(Role $role)
    {
        $this->authorize('update', $role);
        return view('admin.roles.edit', [
            'role' => $role,
            'permissions' => Permission::pluck('name', 'id')
        ]);
    }

    public function update(Request $request, Role $role)
    {
        $this->authorize('update', $role);
        $data = $request->validate([
            'display_name' => 'required',
            'guard_name' => 'required'
        ],[
            'display_name.required' => 'El campo nombre es obligatorio',
            'guard_name.required' => 'El campo nombre de guardia es obligatorio'
        ]);

        $role->update($data);
        $role->permissions()->detach();

        if ($request->has('permissions')) {
            $role->givePermissionTo($request->permissions);
        }

        return redirect()->route('admin.roles.edit', $role)->with('success','El rol fue actualizado correctamente');
    }

    public function destroy(Role $role)
    {
        $this->authorize('delete', $role);
        $role->delete();
        return redirect()->route('admin.roles.index')->with('success','El role fue eliminado correctamente');
    }
}

resources/views/admin/roles/checkboxes.blade.php
@foreach($roles as $role)
    <div class="form-check">
        <input name="roles[]" value="{{ $role->name }}" id="checkRol{{ $role->id }}" type="checkbox" class="form-check-input" {{ $user->roles->contains($role->id) ? 'checked' : ''}}>
        <label class="form-check-label" for="checkRol{{ $role->id }}">{{ $role->name }}</label>
        <br>
        <small class="text-muted">{{ $role->permissions->pluck('name')->implode(', ') }}</small>
    </div>
@endforeach

resources/views/admin/roles/create.blade.php
@extends('layouts.app')
@section('title', 'Crear Rol')
@section('content')
{{ Breadcrumbs::render('roles.crear') }}
<div class="container-fluid mt--6">
        <div class="row">
            <div class="col-md-8 mr-auto ml-auto">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Crear Role</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <h6 class="heading-small text-muted mb-4">Información del Role</h6>
                        <form method="POST" action="{{ route('admin.roles.store') }}">
                            @csrf @method('POST')                            
                            <div class="pl-lg-4">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="name">Identificador</label>
                                        <input name="name" class="form-control" placeholder="Identificador" value="{{ old('name') }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                            <div class="form-group">
                                                <label class="form-control-label" for="display_name">Nombre</label>
                                                <input name="display_name" class="form-control" placeholder="Nombre" value="{{ old('display_name') }}">
                                            </div>
                                        </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="guard_name">Guard</label>
                                            <select class="form-control" name="guard_name">
                                                @foreach (config('auth.guards') as $guardName => $guard)
                                                    <option {{ old('guard_name') === $guardName ? 'selected' : ''}} value="{{ $guardName }}">{{ $guardName }}</option>
                                                @endforeach                                            
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <label class="form-control-label">Permisos</label>
                                        @include('admin.permissions.checkboxes', ['model' => $role])
                                    </div>
                                </div>
                                <div class="row my-4">                                    
                                    <div class="col-lg-6 mr-auto ml-auto">
                                        <div class="form-group">                    
                                            <button class="btn btn-default btn-block">Crear role</button>
                                        </div>
                                    </div>        
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')
@section('title', 'Editar de Roles')
@section('content')
{{ Breadcrumbs::render('roles.editar', $role) }}
<div class="container-fluid mt--6">
        <div class="row">
            <div class="col-md-8 mr-auto ml-auto">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Editar Role</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <h6 class="heading-small text-muted mb-4">Información del Role</h6>
                        <form method="POST" action="{{ route('admin.roles.update', $role) }}">
                            @csrf @method('PUT')                            
                            <div class="pl-lg-4">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label">Identificador</label>
                                            <input class="form-control" placeholder="Nombre" value="{{ $role->name }}" disabled>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="display_name">Nombre</label>
                                            <input name="display_name" class="form-control" placeholder="Nombre" value="{{ old('display_name', $role->display_name) }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="guard_name">Guard</label>
                                            <select class="form-control" name="guard_name">
                                                @foreach (config('auth.guards') as $guardName => $guard)
                                                    <option {{ old('guard_name', $role->guard_name) === $guardName ? 'selected' : ''}} value="{{ $guardName }}">{{ $guardName }}</option>
                                                @endforeach                                            
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <label class="form-control-label">Permisos</label>
                                        @include('admin.permissions.checkboxes', ['model' => $role])
                                    </div>
                                </div>
                                <div class="row my-4">                                    
                                    <div class="col-lg-6 mr-auto ml-auto">
                                        <div class="form-group">                    
                                            <button class="btn btn-default btn-block">Editar role</button>
                                        </div>
                                    </div>        
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')
@section('title', 'Listado de Roles')
@section('content')
{{ Breadcrumbs::render('roles') }}
  <div class="container-fluid mt--6">
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header">
              <div class="row">
                <div class="col-md-8">
                  <h3 class="mb-0">LISTA DE ROLES</h3>
                  <p class="text-sm mb-0">
                    En esta sección puedes ver, editar, eliminar y buscar los roles que creas conveniente.
                  </p>
                </div>
                <div class="col-md-4 text-right">
                  <a href="{{ route('admin.roles.create') }}" class="btn btn-sm btn-default">Crear</a>
                </div>
              </div>              
            </div>
            <div class=" table-responsive py-4">
              <table class="table table-flush" id="myTable">
                <thead class="thead-light">
                  <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Identificador</th>
                    <th>Permisos</th>
                    <th>Guard</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($roles as $role)
                  <tr>
                    <td class="align-middle">{{ $role->id }}</td>
                    <td class="align-middle">{{ $role->name}}</td>     
                    <td class="align-middle">{{ $role->display_name}}</td>
                    <td class="align-middle text-wrap" style="width: 17rem;">
                        {{ $role->permissions->pluck('name')->implode(', ')}}                                          
                    </td>            
                    <td class="align-middle">{{ $role->guard_name }}</td>
                    <td class="align-middle">
                        <a href="{{ route('admin.roles.edit', $role) }}" class="btn btn-info rounded-circle" style="padding-top: 5px;padding-bottom: 5px;padding-right: 10px;padding-left: 10px;">
                            <i class="fas fa-pencil-alt fa-sm"></i>
                        </a>
                        @if($role->id !== 1)
                        <form action="{{ route('admin.roles.destroy', $role) }}" method="POST" style="display: inline">
                            @csrf @method('DELETE')
                            <button class="btn btn-danger rounded-circle" id="deleteButton" style="padding-top: 5px;padding-bottom: 5px;padding-right: 10px;padding-left: 10px;">
                                <i class="fas fa-trash-alt fa-sm"></i>
                            </button>
                        </form>
                        @endif
                    </td>
                  </tr>
                  @endforeach
              </table>
            </div>
          </div>
        </div>
      </div>
      @include('admin.partials.footer')
  </div>
@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('assets/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
@endpush
@push('js')
  <script src="{{ asset('assets/vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script>
    $(document).ready( function () {
        $('#myTable').DataTable({
            "language": @include('admin.partials.datatable_es')
        });    

        $('button#deleteButton').on('click', function(e){
        e.preventDefault();
        // iniciar
        Swal.fire({
          title: '¿Estás seguro?',
          text: "¡No podrás revertir esto!",
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#11cdef',
          cancelButtonColor: '#f5365c',
          confirmButtonText: 'Si, eliminar',
          cancelButtonText: 'Cancelar'
        }).then((result) => {
          if (result.value) {
              Swal.fire(
                'Eliminado',
                'Registro eliminado con éxito.',
                'success'
              )
              $(this).closest("form").submit();
            }
          }) 
        });
    });
</script>
@endpush