routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function(){
    return view('auth.login');
});

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\RolesController;
use App\Http\Controllers\Admin\PermissionsController;
use App\Http\Controllers\Admin\UsersRolesController;
use App\Http\Controllers\Admin\UsersPermissionsController;
use App\Http\Controllers\Admin\TipoCambiosController;


Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    // 'namespace' => 'Admin',
    'middleware' => 'auth'
], function(){
    Route::get('/', [TipoCambiosController::class, 'index']);
    // Usuarios
    Route::resource('users', UsersController::class);
    // // Roles
    Route::resource('roles', RolesController::class)->except(['show']);
    // // Permisos
    Route::resource('permissions', PermissionsController::class)->only(['index', 'edit', 'update']);
    // // Actualizar Roles de Usuario y Permisos de Usuario
    Route::middleware('role:admin')
        ->put('users/{user}/roles', [UsersRolesController::class, 'update'])
        ->name('users.roles.update');
    Route::middleware('role:admin')
        ->put('users/{user}/permissions', [UsersPermissionsController::class, 'update'])
        ->name('users.permissions.update');
    /********************** INICIO MÓDULOS *********************/
    Route::resource('tipocambio', TipoCambiosController::class)->except(['show']);
    /**********************   FIN MÓDULOS  *********************/
});

app/Models/TipoCambio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TipoCambio extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['compra', 'venta', 'user_id', 'deleted_by'];

    public function usuario(){
        return $this->belongsTo(User::class);
    }

    public function scopeAllowed($query)
    {
        if( auth()->user()->can('view', $this)){
            return $query;
        }
        return $query->where('id', auth()->id());
    }
}

app/Http/Controllers/Admin/TipoCambiosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\TipoCambio;
use Illuminate\Http\Request;
use App\Http\Requests\TipoCambioRequest;

class TipoCambiosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('view', new TipoCambio);
        $tipoCambios = TipoCambio::orderBy('created_at', 'DESC')->get();
        return view('admin.tipocambio.index', compact('tipoCambios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', new TipoCambio);
        $tipocambio = new TipoCambio;
        return view('admin.tipocambio.create', compact('tipocambio'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TipoCambioRequest $request)
    {
        $this->authorize('create', new TipoCambio);
        $tipoCambio = new TipoCambio;
        $tipoCambio->compra = $request->compra;
        $tipoCambio->venta = $request->venta;
        $tipoCambio->user_id = auth()->id();
        $tipoCambio->save();
        return redirect()->route('admin.tipocambio.index')->with('success', 'Tipo de cambio creado con éxito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(TipoCambio $tipocambio_id, $id)
    {
        $this->authorize('update', $tipocambio_id);
        $tipocambio = TipoCambio::find($id);
        return view('admin.tipocambio.edit', compact('tipocambio'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TipoCambio $tipocambio, TipoCambioRequest $request)
    {
        $this->authorize('update', $tipocambio);
        $tipocambio->update( $request->validated() );
        return redirect()->route('admin.tipocambio.index')->with('success','Tipo de cambio actualizado con éxito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(TipoCambio $tipocambio)
    {
        $this->authorize('delete', $tipocambio);
        $tipocambio->delete();
        return redirect()->route('admin.tipocambio.index')->with('success', 'Tipo de cambio eliminado con éxito');
    }
}

app/Http/Controllers/Api/TipoCambiosController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\TipoCambio;
use Illuminate\Http\Request;

class TipoCambiosController extends Controller
{
    public function index()
    {
        $tipoCambios = TipoCambio::select('venta', 'compra')->orderBy('created_at', 'DESC')->get();
        return response()->json(['data' => $tipoCambios], 200);
    }


    public function ultimo()
    {
        $tipoCambios = TipoCambio::select('venta', 'compra')->orderBy('created_at', 'DESC')->limit(1)->get();
        return response()->json(['data' => $tipoCambios], 200);
    }


}

resources/views/admin/tipocambio/_form.blade.php
<div class="row">
    <div class="col-lg-12">
        <div class="form-group">
            <label class="form-control-label" for="compra">Precio de compra</label>
            <input name="compra" class="form-control" placeholder="Ingresar precio de compra" type="text" value="{{ old('compra', $tipocambio->compra) }}">
        </div>
    </div>
    <div class="col-lg-12">
        <div class="form-group">
            <label class="form-control-label" for="venta">Precio de venta</label>
            <input name="venta" class="form-control" placeholder="Ingresar precio de venta" type="text" value="{{ old('venta', $tipocambio->venta) }}">
        </div>
    </div>
</div>

resources/views/admin/tipocambio/create.blade.php
@extends('layouts.app')
@section('title', 'Crear tipo de cambio')
@section('content')
{{ Breadcrumbs::render('tipocambios.crear') }}
<div class="container-fluid mt--6">
        <div class="row">
            <div class="col-md-8 mr-auto ml-auto">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Crear Tipo de cambio</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.tipocambio.store') }}">
                            @csrf @method('POST')
                            <div class="pl-lg-4">
                                @include('admin.tipocambio._form')
                                <div class="row my-4">
                                    <div class="col-lg-6 mr-auto ml-auto">
                                        <div class="form-group">
                                            <button class="btn btn-default btn-block">GRABAR</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection

resources/views/admin/tipocambio/edit.blade.php
@extends('layouts.app')
@section('title', 'Editar tipo de cambio')
@section('content')
{{ Breadcrumbs::render('tipocambios.editar', $tipocambio) }}
<div class="container-fluid mt--6">
        <div class="row">
            <div class="col-md-8 mr-auto ml-auto">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Editar Tipo de cambio</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.tipocambio.update', $tipocambio->id ) }}">
                            @csrf @method('PUT')
                            <div class="pl-lg-4">
                                @include('admin.tipocambio._form')
                                <div class="row my-4">
                                    <div class="col-lg-6 mr-auto ml-auto">
                                        <div class="form-group">
                                            <button class="btn btn-default btn-block">ACTUALIZAR</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection

resources/views/admin/tipocambio/index.blade.php
@extends('layouts.app')
@section('title', 'Listado')
@section('content')
{{ Breadcrumbs::render('tipocambios') }}
  <div class="container-fluid mt--6">
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header">
              <div class="row">
                <div class="col-8">
                  <h2 class="mb-0">Listado</h2>
                  <p class="text-sm mb-0">
                </div>
                @if(Auth::user()->hasPermissionTo('crear-tipo-cambio') || Auth::user()->hasRole('admin'))
                <div class="col-4 text-right">
                  <a class="btn btn-default text-white" href="{{ route('admin.tipocambio.create')}}">Nuevo registro</a>
                </div>
                @endif
              </div>
            </div>
            <div class="table-responsive py-4">
              <table id="table-posts" class="table table-flush">
                <thead class="thead-light">
                  <tr>
                    <th>ID</th>
                    <th>Precio Compra</th>
                    <th>Precio Venta</th>
                    <th>Fecha</th>
                    @if( Auth::user()->hasAnyPermission(['editar-tipo-cambio']) || Auth::user()->hasRole('admin'))
                      <th>Acciones</th>
                    @endif
                  </tr>
                </thead>
                <tbody>
                  @foreach ($tipoCambios as $tipocambio)
                  <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $tipocambio->compra }}</td>
                    <td>{{ $tipocambio->venta }}</td>
                    <td>{{ $tipocambio->created_at }}</td>
                    <td>
                      @if( Auth::user()->hasPermissionTo('actualizar-tipo-cambio') || Auth::user()->hasRole('admin'))
                        <a href="{{ route('admin.tipocambio.edit', $tipocambio->id) }}" class="btn btn-info rounded-circle" style="padding-top: 5px;padding-bottom: 5px;padding-right: 10px;padding-left: 10px;">
                          <i class="fas fa-pencil-alt fa-sm"></i>
                        </a>
                      @endif
                      @if( Auth::user()->hasPermissionTo('eliminar-tipo-cambio') || Auth::user()->hasRole('admin'))
                        <form action="{{ route('admin.tipocambio.destroy', $tipocambio) }}" method="POST" style="display: inline">
                          @csrf @method('DELETE')
                          <button class="btn btn-danger rounded-circle" id="deleteButton" style="padding-top: 5px;padding-bottom: 5px;padding-right: 10px;padding-left: 10px;">
                            <i class="fas fa-trash-alt fa-sm"></i>
                          </button>
                        </form>
                      @endif
                    </td>
                  </tr>
                  @endforeach
              </table>
            </div>
          </div>
        </div>
      </div>
      @include('admin.partials.footer')
  </div>
@endsection
@push('css')
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
@endpush
@push('js')
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
  <script src="{{ asset('js/data-dataTable.js') }}"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8.17.6/dist/sweetalert2.all.min.js"></script>
  <script>
    $('button#deleteButton').on('click', function(e){
      e.preventDefault();
      // iniciar
      Swal.fire({
        title: '¿Estás seguro?',
        text: "¡No podrás revertir esto!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#11cdef',
        cancelButtonColor: '#f5365c',
        confirmButtonText: 'Si, eliminar',
        cancelButtonText: 'Cancelar'
      }).then((result) => {
        if (result.value) {
          Swal.fire(
            'Eliminado',
            'Su archivo ha sido eliminado.',
            'success'
          )
          $(this).closest("form").submit();
        }
      })
      // fin
    });
  </script>
@endpush