routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function(){
    return view('auth.login');
});

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\RolesController;
use App\Http\Controllers\Admin\PermissionsController;
use App\Http\Controllers\Admin\UsersRolesController;
use App\Http\Controllers\Admin\UsersPermissionsController;
use App\Http\Controllers\Admin\TipoCambiosController;


Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    // 'namespace' => 'Admin',
    'middleware' => 'auth'
], function(){
    Route::get('/', [TipoCambiosController::class, 'index']);
    // Usuarios
    Route::resource('users', UsersController::class);
    // // Roles
    Route::resource('roles', RolesController::class)->except(['show']);
    // // Permisos
    Route::resource('permissions', PermissionsController::class)->only(['index', 'edit', 'update']);
    // // Actualizar Roles de Usuario y Permisos de Usuario
    Route::middleware('role:admin')
        ->put('users/{user}/roles', [UsersRolesController::class, 'update'])
        ->name('users.roles.update');
    Route::middleware('role:admin')
        ->put('users/{user}/permissions', [UsersPermissionsController::class, 'update'])
        ->name('users.permissions.update');
    /********************** INICIO MÓDULOS *********************/
    Route::resource('tipocambio', TipoCambiosController::class)->except(['show']);
    /**********************   FIN MÓDULOS  *********************/
});

app/Models/User.php
<?php

namespace App\Models;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'password', 'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function scopeAllowed($query)
    {
        if( auth()->user()->can('view', $this)){
            return $query;
        }
        return $query->where('id', auth()->id());
    }

    public function setPasswordAttribute($password){
        $this->attributes['password'] = Hash::make($password);
    }

    public function getRoleDisplayNames(){
        return $this->roles->pluck('display_name')->implode(', ');
    }

    public function tipoCambio(){
        return $this->hasMany(TipoCambio::class);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\UserRequest;
use App\Models\User;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::allowed()->get();
        return view('admin.users.index', compact('users'));
    }

    public function create()
    {
        $user = new User;
        $this->authorize('create', $user);
        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name', 'id');
        return view('admin.users.create', compact('user','roles', 'permissions'));
    }

    public function store(UserRequest $request)
    {
        $this->authorize('create', new User);
        $user = User::create($request->validated());
        if($request->filled('roles')){
            $user->assignRole($request->roles);
        }
        if($request->filled('permissions')){
            $user->givePermissionTo($request->permissions);
        }
       return redirect()->route('admin.users.index')->with('success','El usuario ha sido creado');
    }

    public function show(User $user)
    {
        $this->authorize('view', $user);
        return view('admin.users.show', compact('user'));
    }

    public function edit(User $user)
    {
        $this->authorize('update', $user);
        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name', 'id');
        return view('admin.users.edit', compact('user', 'roles', 'permissions'));
    }

    public function update(User $user, UserRequest $request){
        $this->authorize('update', $user);
        if( $request->hasFile('avatar') ){
            Storage::delete($user->avatar);
            $user->fill( $request->validated() );
            $user->avatar = $request->file('avatar')->store('img/usuario');
            $user->save();
        } else {
            $user->update( array_filter($request->validated()) );
        }
        return redirect()->route('admin.users.edit', $user)->with('success','Usuario actualizado');
    }

    public function destroy(User $user)
    {
        $this->authorize('delete', $user);
        Storage::delete($user->avatar);
        $user->delete();
        return redirect()->route('admin.users.index')->with('success','Usuario eliminado');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')
@section('title', 'Crear usuario')
@section('content')
{{ Breadcrumbs::render('usuarios.crear') }}
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-md-8 mr-auto ml-auto">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Crear Usuario</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        
                        <h6 class="heading-small text-muted mb-4">Información del Usuario</h6>
                        <form method="POST" action="{{ route('admin.users.store') }}">
                            @csrf @method('POST')
                            <div class="pl-lg-4">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="name">Nombre</label>
                                            <input name="name" class="form-control" placeholder="Nombre" value="{{ old('name') }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="username">Usuario</label>
                                            <input name="username" class="form-control" placeholder="Nombre de usuario" value="{{ old('username') }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="email">Email</label>
                                            <input name="email" class="form-control" placeholder="hola@email.com" value="{{ old('email') }}">
                                        </div>
                                    </div>                                    
                                    <div class="col-lg-6">
                                        <label class="form-control-label">Roles</label>
                                        @include('admin.roles.checkboxes')
                                    </div>
                                    <div class="col-lg-6">
                                        <label class="form-control-label">Permisos</label>
                                        @include('admin.permissions.checkboxes', ['model' => $user])
                                    </div>
                                </div>
                                <div class="row my-4">
                                    <div class="col-lg-6 mr-auto ml-auto">
                                        <div class="form-group">
                                            <button class="btn btn-default btn-block">Crear usuario</button>
                                        </div>
                                    </div>
                                    <div class="col-12 text-center">
                                        <span class="text-default h5">La contraseña generada por defecto es: 123456</span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')
@section('title', 'Editar usuario')
@section('content')
{{ Breadcrumbs::render('usuarios.editar', $user) }}
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">Editar Perfil</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        @if($errors->any())
                            <ul class="list-group">
                                @foreach($errors->all() as $error)
                                    <li class="py-1 h5 list-group-item bg-warning text-secondary">{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif
                        <h6 class="heading-small text-muted mb-4">Información del Usuario</h6>
                        <form method="POST" action="{{ route('admin.users.update', $user) }}" enctype="multipart/form-data">
                            @csrf @method('PUT')
                            <div class="pl-lg-4">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="avatar">Avatar</label>
                                            <input type="file" name="avatar" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label class="form-control-label" for="name">Nombre</label>
                                            <input name="name" class="form-control" placeholder="Nombre" value="{{ old('name', $user->name) }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="email">Email</label>
                                            <input name="email" class="form-control" placeholder="hola@email.com" value="{{ old('email', $user->email) }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="username">Nombre de usuario</label>
                                            <input name="username" class="form-control" placeholder="Nombre de usuario" value="{{ old('username', $user->username) }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="password">Contraseña</label>
                                            <input type="password" name="password" class="form-control" placeholder="Contraseña">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="password_confirmation">Repite la contraseña</label>
                                            <input type="password" name="password_confirmation" class="form-control" placeholder="Repite la contraseña">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 mr-auto ml-auto">
                                        <div class="form-group">
                                            <button class="btn btn-default btn-block">Actualizar Perfil</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="row align-items-center">
                                    <div class="col-8">
                                        <h3 class="mb-0">Roles</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                @role('admin')
                                <form method="POST" action="{{ route('admin.users.roles.update', $user) }}">
                                    @csrf @method('PUT')
                                    @include('admin.roles.checkboxes')
                                    <button class="mt-3 btn btn-default btn-block">Actualizar Roles</button>
                                </form>
                                @else
                                    <ul class="list-group">
                                        @forelse ($user->roles as $role)
                                            <li class="list-group-item">{{ $role->name }}</li>
                                        @empty
                                            <li class="list-group-item">No tienes roles</li>
                                        @endforelse
                                    </ul>
                                    @endrole
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="row align-items-center">
                                    <div class="col-8">
                                        <h3 class="mb-0">Permisos</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                @role('admin')
                                <form method="POST" action="{{ route('admin.users.permissions.update', $user) }}">
                                    @csrf @method('PUT')
                                    @include('admin.permissions.checkboxes', ['model' => $user])
                                    <button class="mt-3 btn btn-default btn-block">Actualizar Permisos</button>
                                </form>
                                @else
                                    <ul class="list-group">
                                        @forelse ($user->permissions as $permission)
                                            <li class="list-group-item">{{ $permission->name }}</li>
                                        @empty
                                            <li class="list-group-item">No tienes permisos</li>
                                        @endforelse
                                    </ul>
                                    @endrole
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')
@section('title', 'Listado de Usuarios')
@section('content')
{{ Breadcrumbs::render('usuarios') }}
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-8">
              <h3 class="mb-0">LISTA DE USUARIOS</h3>
              <p class="text-sm mb-0">
                En esta sección puedes ver, editar, eliminar y buscar el usuario que creas conveniente.
              </p>
            </div>
            <div class="col-md-4 text-right">
              <a href="{{ route('admin.users.create') }}" class="btn btn-sm btn-default">Crear</a>
            </div>
          </div>
        </div>
        <div class="table-responsive py-4">
          <table class="table table-flush" id="myTable">
            <thead class="thead-light">
              <tr>
                <th>ID</th>
                <th>Avatar</th>
                <th>Nombre Completo</th>
                <th>Nombre de usuario</th>
                <th>Correo</th>
                <th>Roles</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>ID</th>
                <th>Avatar</th>
                <th>Nombre Completo</th>
                <th>Nombre de usuario</th>
                <th>Correo</th>
                <th>Roles</th>
                <th>Acciones</th>
              </tr>
            </tfoot>
            <tbody>
            @foreach ($users as $user)
              <tr>
                <td class="align-middle">{{ $user->id }}</td>
                <td class="align-middle">
                  @if($user->avatar != null)
                    <img height="50px" width="50px" class="rounded-circle shadow-lg" alt="{{ $user->name }}" src="/storage/{{ $user->avatar }}" height="50">
                  @else
                    <img class="rounded-circle shadow-lg"  alt="{{ $user->name }}" src="{{ asset('assets/img/placeholder.jpg') }}" height="50">
                  @endif
                </td>
                <td class="align-middle">{{ $user->name}}</td>
                <td class="align-middle">{{ $user->username}}</td>
                <td class="align-middle">{{ $user->email }}</td>
                <td class="align-middle">{{ $user->getRoleDisplayNames() }}</td>
                <td class="align-middle">
                    <a href="{{ route('admin.users.show', $user) }}" class="btn btn-info rounded-circle btn-acciones">
                      <i class="fas fa-eye fa-sm"></i>
                    </a>

                    <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-success rounded-circle btn-acciones">
                      <i class="fas fa-pencil-alt fa-sm"></i>
                    </a>
                    <form action="{{ route('admin.users.destroy', $user) }}" method="POST" style="display: inline">
                      @csrf @method('DELETE')
                      <button class="btn btn-danger rounded-circle btn-acciones" id="deleteButton">
                        <i class="fas fa-trash-alt fa-sm"></i>
                      </button>
                    </form>
                </td>
              </tr>
            @endforeach
          </table>
        </div>
      </div>
    </div>
  </div>
  @include('admin.partials.footer')
</div>
@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('assets/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
@endpush
@push('js')
  <script src="{{ asset('assets/vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script>
    $(document).ready( function () {
        $('#myTable').DataTable({
            "language": @include('admin.partials.datatable_es')
        });    

        $('button#deleteButton').on('click', function(e){
        e.preventDefault();
        // iniciar
        Swal.fire({
          title: '¿Estás seguro?',
          text: "¡No podrás revertir esto!",
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#11cdef',
          cancelButtonColor: '#f5365c',
          confirmButtonText: 'Si, eliminar',
          cancelButtonText: 'Cancelar'
        }).then((result) => {
          if (result.value) {
              Swal.fire(
                'Eliminado',
                'Registro eliminado con éxito.',
                'success'
              )
              $(this).closest("form").submit();
            }
          }) 
        });
    });
</script>
@endpush

resources/views/admin/users/show.blade.php
@extends('layouts.app')
@section('title', 'Perfil de usuario')
@section('content')
{{ Breadcrumbs::render('usuarios.ver', $user) }}
    <div class="container-fluid mt--6">
        <div class="row">
            {{--PERFIL--}}
            <div class="col-lg-3 col-md-6 col-12">
                <div class="card card-profile">
                    <img height="80px" src="{{ asset('assets/img/fondos/fondo-01.jpg')}}" alt="Image placeholder" class="card-img-top">
                    <div class="row justify-content-center">
                        <div class="col-lg-3 order-lg-2">
                            <div class="card-profile-image">
                                @if($user->avatar != null)                        
                                    <img class="rounded-circle shadow-lg" alt="{{ $user->name }}" src="/storage/{{ $user->avatar }}">
                                @else
                                    <img class="rounded-circle shadow-lg" alt="{{ $user->name }}" src="{{ asset('assets/img/placeholder.jpg') }}">
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="card-body pt-6">
                        <div class="text-center">
                            <h5 class="h3">{{ $user->name }}</h5>
                            <div class="h5 font-weight-300">
                                <i class="ni location_pin mr-2"></i>{{ $user->getRoleDisplayNames() }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="card-profile-stats my-0 py-0">
                                    <div class="row d-inline-block">
                                        <div class="col text-left">
                                            <span class="description">Email</span>
                                        </div>
                                        <div class="col">
                                        <span class="description text-default">
                                            <b>{{ $user->email }}</b>
                                        </span>
                                        </div>
                                    </div>
                                    <hr class="divider my-0">
                                    <div class="row d-inline-block">
                                        <div class="col text-left">
                                            <span class="description">Nombre de usuario</span>
                                        </div>
                                        <div class="col text-left">
                                        <span class="description text-default">
                                            <b>{{ $user->username }}</b>
                                        </span>
                                        </div>
                                    </div>
                                    @if($user->roles->count())
                                        <hr class="divider my-0">
                                        <div class="row d-inline-block">
                                            <div class="col text-left">
                                                <span class="description">Roles</span>
                                            </div>
                                            <div class="col text-left">
                                            <span class="description text-default">
                                                <b>{{ $user->getRoleDisplayNames() }}</b>
                                            </span>
                                            </div>
                                        </div>
                                    @endif
                                    <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-default btn-lg btn-block text-white">Editar</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            {{--ROLES--}}
            <div class="col-lg-3 col-md-6 col-12">
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header">
                        <!-- Title -->
                        <h5 class="h3 mb-0">Roles</h5>
                    </div>
                    <!-- Card body -->
                    <div class="card-body">
                        <!-- List group -->
                        <ul class="list-group list-group-flush list my--3">
                            @forelse($user->roles as $role)
                                <li class="list-group-item px-0">
                                    <div class="row align-items-center">
                                        <div class="col">
                                            <p class="h4 mb-0">
                                                {{ $role->display_name }}
                                            </p>
                                            @if($role->permissions->count())
                                                <hr class="divider">
                                                <i class="ni ni-app"></i>
                                                <small>Permisos: {{ $role->permissions->pluck('display_name')->implode(', ') }}</small>
                                            @endif
                                            @unless($loop->last)
                                                <hr>
                                            @endunless
                                        </div>
                                    </div>
                                </li>
                            @empty
                                <small class="text-muted">No tiene roles</small>
                            @endforelse
                        </ul>
                    </div>
                </div>
            </div>
            {{--PERMISOS--}}
            <div class="col-lg-3 col-md-6 col-12">
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header">
                        <!-- Title -->
                        <h5 class="h3 mb-0">Permisos extra</h5>
                    </div>
                    <!-- Card body -->
                    <div class="card-body">
                        <!-- List group -->
                        <ul class="list-group list-group-flush list my--3">
                            @forelse($user->permissions as $permission)
                            <small>
                                {{ $permission->display_name }}
                            </small>
                            @empty
                                <small class="text-muted">No tiene permisos adicionales</small>
                            @endforelse
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection