routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function(){
    return view('auth.login');
});

Auth::routes(['register' => false, 'reset' => false, 'verify' => false]);

use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\RolesController;
use App\Http\Controllers\Admin\PermissionsController;
use App\Http\Controllers\Admin\UsersRolesController;
use App\Http\Controllers\Admin\UsersPermissionsController;
use App\Http\Controllers\Admin\TipoCambiosController;


Route::group([
    'as' => 'admin.',
    'prefix' => 'admin',
    // 'namespace' => 'Admin',
    'middleware' => 'auth'
], function(){
    Route::get('/', [TipoCambiosController::class, 'index']);
    // Usuarios
    Route::resource('users', UsersController::class);
    // // Roles
    Route::resource('roles', RolesController::class)->except(['show']);
    // // Permisos
    Route::resource('permissions', PermissionsController::class)->only(['index', 'edit', 'update']);
    // // Actualizar Roles de Usuario y Permisos de Usuario
    Route::middleware('role:admin')
        ->put('users/{user}/roles', [UsersRolesController::class, 'update'])
        ->name('users.roles.update');
    Route::middleware('role:admin')
        ->put('users/{user}/permissions', [UsersPermissionsController::class, 'update'])
        ->name('users.permissions.update');
    /********************** INICIO MÓDULOS *********************/
    Route::resource('tipocambio', TipoCambiosController::class)->except(['show']);
    /**********************   FIN MÓDULOS  *********************/
});

resources/views/admin/partials/breadcrumbs.blade.php
<div class="header bg-info pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              @if (count($breadcrumbs))
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                    @foreach ($breadcrumbs as $breadcrumb)
                        @if ($breadcrumb->url && !$loop->last)
                            <li class="breadcrumb-item"><a href="{{ $breadcrumb->url }}"><i class="fas {{ $breadcrumb->icon }}"></i> {{ $breadcrumb->title }}</a></li>
                        @else
                            <li class="breadcrumb-item active" aria-current="page">{{ $breadcrumb->title }}</li>
                        @endif
                    @endforeach
                </ol>
            @endif
            </nav>
          </div>
        </div>
      </div>
    </div>
</div>

resources/views/admin/partials/datatable_es.blade.php
{
    "sProcessing": "Procesando...",
    "sLengthMenu": "Mostrar _MENU_ registros",
    "sZeroRecords": "No se encontraron resultados",
    "sEmptyTable": "Ningún dato disponible en esta tabla",
    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
    "sInfoPostFix": "",
    "sSearch": "Buscar:",
    "sUrl": "",
    "sInfoThousands": ",",
    "sLoadingRecords": "Cargando...",
    "oPaginate": {
        "sFirst": "Primero",
        "sLast": "Último",
        "sNext": "<i class='fas fa-angle-right'></i>",
        "sPrevious": "<i class='fas fa-angle-left'></i>"
    },
    "oAria": {
        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
    }
}

resources/views/admin/partials/footer.blade.php
<footer class="footer pt-0">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="copyright text-center text-muted">
          &copy; 2021 <a href="#" class="font-weight-bold ml-1 text-info" target="_blank">Desarrollado</a>
        </div>
      </div>
    </div>
</footer>

resources/views/admin/partials/nav.blade.php
<nav class="navbar navbar-top navbar-expand navbar-dark bg-info border-bottom">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <h3 class="text-white">SISTEMA TIPO DE CAMBIO</h3>
        <ul class="navbar-nav align-items-center  ml-md-auto ">

          <li class="nav-item d-xl-none">
            <!-- Sidenav toggler -->
            <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
              <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
              </div>
            </div>
          </li>
        </ul>

        <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
          <li class="nav-item dropdown">
            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="media align-items-center">
                <span class="avatar avatar-sm rounded-circle">
                    @if(Auth::user()->avatar != null)
                        <img class="rounded-circle shadow-lg" alt="{{ Auth::user()->name }}" src="/storage/{{ Auth::user()->avatar }}" height="36px" width="36px">
                    @else
                    <img class="mx-2 h-24 w-24 rounded-full object-cover" src="https://ui-avatars.com/api/?name={{ Auth::user()->name }}&color=ffffff&background=86dc23&size=80" alt="{{ Auth::user()->name }}">
                    @endif
                </span>
                <div class="media-body  ml-2  d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold">{{ Auth::user()->name }}</span>
                </div>
              </div>
            </a>
            <div class="dropdown-menu  dropdown-menu-right ">
              <div class="dropdown-header noti-title">
                <h6 class="text-overflow m-0">Bienvenido</h6>
              </div>
              <a href="{{ route('admin.users.show', auth()->user()) }}" class="dropdown-item">
                <i class="ni ni-single-02"></i>
                <span>Mi perfil</span>
              </a>
              @if(Auth::user()->hasRole('admin'))
              <a href="{{ route('admin.roles.index') }}" class="dropdown-item">
                <i class="fas fa-gem"></i>
                <span>Roles</span>
              </a>
              <a href="{{ route('admin.permissions.index') }}" class="dropdown-item">
                <i class="fas fa-key"></i>
                <span>Permisos</span>
              </a>
              @endif
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ route('logout') }}"
              onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                <i class="ni ni-user-run"></i>
                <span>Desconectar</span>
              </a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
              </form>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

resources/views/admin/partials/sidenav.blade.php
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <div class="sidenav-header  d-flex  align-items-center">
        <a class="navbar-brand" href="{{ url('admin') }}">
          LOGO
        </a>
        <div class=" ml-auto ">
          <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <hr class="my-3">
          <h6 class="navbar-heading p-0 text-muted">MÓDULO</h6>
          <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link {{ activarLink('admin.tipocambio.index') }}" href="{{ route('admin.tipocambio.index') }}" >
                  <i class="fas fa-dollar-sign"></i>
                  <span class="nav-link-text">Tipo de cambio</span>
                </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>